name: Release Please

on:
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: googleapis/release-please-action@5a86462a201d297e9f70b1cdca723b21da60b0fc # v4.4
        with:
          release-type: node
